name: Run packer build on a template file

on: [push]
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Packer build
        uses: ./
        with:
          templateFile: 'template.json'
          variablesFile: 'vars.json'
          workingDir: '.'
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
